name: Build csp-hash-gen
on:
  push:
    branches: ["main"]

jobs:
  cd:
    name: Build, test and publish csp-hash-gen
    runs-on: ubuntu-latest
    permissions: write-all # This is needed to create a new git tag

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from package.json
        id: extract_version
        run: echo ::set-output name=VERSION::$(node -p "require('./package.json').version")

      - name: Check if package.json version is listed in npm registry
        id: check_npm_version
        run: |
          VERSION=${{ steps.extract_version.outputs.VERSION }}
          if npm view csp-hash-gen@$VERSION > /dev/null; then
            echo "Version $VERSION exists in npm registry"
            exit 1
          fi

      - name: Create Release
        id: create_release
        run: |
          gh release create v${{ steps.extract_version.outputs.VERSION }} --title "v${{ steps.extract_version.outputs.VERSION }}" --notes "${{ steps.github_release.outputs.changelog }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run deploy
        name: Deploy to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}